name: Build TLD list

on:
  push:
    branches:
      - main
      - features/**
      - dependabot/**
  pull_request:
    branches:
      - main
  schedule:
      # https://crontab.guru/#41_9_*_*_6
    - cron: "41 9 * * 6"

permissions:
  contents: read

jobs:
  docker:
    permissions:
      contents: write  # for Git to git push
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Checkout the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Build the container and run the generator
        run: docker compose up

      - name: Git config
        run: |
          git config --global user.name "Ryan Parman (Automated)"
          git config --global user.email "ryan@ryanparman.com"
          git pull --rebase --autostash

      - name: Git commit
        run: |
          if [[ "$(git status -sb | wc -l)" == "1" ]]; then
            echo "No changes to commit."
          else
            git add .
            git commit -m "Automated commit: $(date +"%Y-%m-%dT%T%z")"
            git push origin main
          fi
